version: 2.1

jobs:
  build:
    docker:
      - image: cibuilds/docker:latest
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build a Docker image"
          command: |
            docker build -t shunak/nodejs-express .
      - run:
          name: "Push to DockerHub"
          command: |
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin && \
            docker push shunak/nodejs-express


            